### ISSUE TITLE
feat: 希望能新增公車站牌的api

### ISSUE THREAD

**Issue by pedestrianlove** [NTHU-SA/NTHU-Data-API#122]
如題，如果要做行程規劃(Google行程 + 公車 + Google行程)的話，
有站牌的列表跟位置會方便很多，就不需要寫死。

所以希望公車的API可以多一個:
```
https://api.nthusa.tw/buses/stops/
```

感謝🙏

**Comment by iwtba4188** [comment]
感謝建議，你的意思是回傳類似下方的 schema 嗎？
```json
[{
  "stop_name": "string",
  "latitude": "string",
  "longitude": "string"
},
...
]
```

**Comment by pedestrianlove** [comment]
> 感謝建議，你的意思是回傳類似下方的 schema 嗎？
> 
> ```json
> [{
>   "stop_name": "string",
>   "latitude": "string",
>   "longitude": "string"
> },
> ...
> ]
> ```

是的，感謝補充😂
