### ISSUE TITLE
bug(libraries): 圖書館因故閉館時無法正常回傳

### ISSUE THREAD

**Issue by iwtba4188** [NTHU-SA/NTHU-Data-API#60]
## Bug Report

**Current Behavior**
`404: Not Found`

**Expected behavior/code**
`200: OK`

**Description**
- 如果圖書館因故閉館，則圖書館 API 回傳：
```javascript
var openhour ='2023-12-24 (Sun)<br />不提供服務';
```
- 該 response 無法 match 目前處理的 regex：
```python
    match = re.search(
        r"(\d{4}-\d{2}-\d{2}\s+\([\w]+\))<br />(\d{2}:\d{2})-(\d{2}:\d{2})", text
    )
```

**Possible Solution**
把 regex 寫成可以處理這種情況的（~~但我懶得馬上改所以來開 Issue~~）

**Comment by l7wei** [comment]
笑死原來這個是這個原因==

**Comment by l7wei** [comment]
#111
