### ISSUE TITLE
bug(dining): /dining/ unsystematic format

### ISSUE THREAD

**Issue by Joshimello** [NTHU-SA/NTHU-Data-API#69]
**Expected output**
I assume this is the expected output
![opera_Fjg2AYZ4Sh](https://github.com/NTHU-SA/NTHU-Data-API/assets/74640729/83d1b973-ed7b-4f32-8863-4b60494839c4)

**Odd cases**
There are cases of empty entries (in this case, no time and no name)
![opera_MOraeDTiX0](https://github.com/NTHU-SA/NTHU-Data-API/assets/74640729/9f244dd8-e093-4f4b-88fe-59f5dd26eddb)

There are cases with ambiguous time slots (very random pattern, Chinese weekday time in weekend slot, or all data in weekday slot with Chinese format instead)
![opera_WiEsdqhJE3](https://github.com/NTHU-SA/NTHU-Data-API/assets/74640729/c55cc0a9-c71d-426b-b19a-5f84660c1a12)

Thanks

**Comment by iwtba4188** [comment]
> There are cases of empty entries (in this case, no time and no name)

我剛剛看起來是沒有問題的，請問有辦法提供更詳細的發生情況嗎><？
剛剛的結果供參：[240114175320_dining_download.json](https://github.com/NTHU-SA/NTHU-Data-API/files/13930991/240114175320_dining_download.json)。

> There are cases with ambiguous time slots (very random pattern, Chinese weekday time in weekend slot, or all data in weekday slot with Chinese format instead)

因為[學校網頁](https://ddfm.site.nthu.edu.tw/p/404-1494-256455.php?Lang=zh-tw)原始資料的時間欄位並沒有一致的格式，我們目前沒有特別做資料清洗，之後會再討論看看需不需要幫忙處理。

感謝！

**Comment by Joshimello** [comment]
> 我剛剛看起來是沒有問題的，請問有辦法提供更詳細的發生情況嗎><？
Oh my bad my bad！可能是我這裏的問題 xP
> 因為學校網頁原始資料的時間欄位並沒有一致的格式，我們目前沒有特別做資料清洗，之後會再討論看看需不需要幫忙處理。
瞭解~ 謝謝！我就先暫時手動修改.
